################################################################
#
################################################################
language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2

script:
  - mvn install

after_success:
  - bash <(curl -s https://codecov.io/bash)